### ISSUE TITLE
[Crash]: The game crashes if the mod is installed.

### ISSUE THREAD

**Issue by NintendoPSproG2** [Fuzss/forgeconfigapiport-fabric#13]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.18.1

### Mod Version (Required)

v.3.2.3

### Notes (Required)

I'm trying to use the latest version of the 1.18 version to use Shoulder Surfing Reloaded, a mod that requires this api. But this exact version crashes the game, and the mod needs this version. Maybe it's an incompatibility issue?

### Crash Report (Required)

https://gist.github.com/NintendoPSproG2/0c3966cc043dba534f9a79cf8ec4ee9b
This was all I could find.

### latest.log (Optional)

https://gist.github.com/NintendoPSproG2/23e91818c8afb02ae17148744ee84e94

**Comment by Fuzss** [comment]
The issue is I bundle a version of Fabric Api that is incompatible with MC 1.18.1. I'll remove the bundled Fabric Api again in the next release to avoid these kinds of issues.

**Comment by Fuzss** [comment]
Fabric Api is no longer bundled in the latest build and it does work properly on 1.18.1 now. 

Shoulder Surfing Reloaded requires a version of Fabric Api that only supports 1.18.2 unfortunately though. If you really want to use it on 1.18.1 instead of 1.18.2 take a look at this (it allows you to remove dependencies from mods): https://fabricmc.net/wiki/tutorial:dependency_overrides
