### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [Fuzss/forgeconfigapiport-fabric#2]

**Comment by Fuzss** [comment]
It's a library for devs, you only need to install it when another mod tells you to do so.

For what it does, it allows for creating config files for mods in exactly the same way as is done on the Forge mod loader, so it's really easy for devs to maintain a mod on both ecosystems.

**Comment by mateus3c** [comment]
hey I know this is very old but what does this do on Forge? I understand the use for it on Fabric but why is the mod also available on Forge/Neoforge?

**Comment by Fuzss** [comment]
That's intended for mods that support all three mod loaders: Fabric, Forge and NeoForge.
The dev can then e.g. use the NeoForge config system on Forge and Fabric, or the Forge system on NeoForge and Fabric.
It's mostly a convenience, since the config system is very similar between Forge and NeoForge.
As an example, a mod using FCAP this way is [Shoulder Surfing Reloaded](https://www.curseforge.com/minecraft/mc-mods/shoulder-surfing-reloaded).
